#!/bin/bash

echo "🐰 Emilia's GitHub Repository Setup"
echo "=================================="

# GitHub Repository erstellen (manuell)
echo ""
echo "📝 MANUELLE GITHUB REPOSITORY ERSTELLUNG:"
echo "========================================"
echo ""
echo "1. 🌐 Öffne: https://github.com"
echo "2. 👤 Klicke 'Sign up' oder 'Sign in'"
echo "3. ➕ Klicke '+ New repository'"
echo "4. 📝 Name: emilia-lernplattform"
echo "5. 📄 Description: Kostenlose IHK Lernplattform für Büromanagement"
echo "6. 🔓 Public auswählen"
echo "7. ❌ 'Add a README file' ABWÄHLEN"
echo "8. 🚀 Klicke 'Create repository'"
echo ""
echo "🔗 DAN DIESE BEFEHLE AUSFÜHREN:"
echo "================================"
echo ""
echo "cd /opt/data/emilia-lernplattform"
echo "git remote add origin https://github.com/DEIN-BENUTZERNAME/emilia-lernplattform.git"
echo "git push -u origin master"
echo ""
echo "📱 DEINE WEBSEITE DANN UNTER:"
echo "============================"
echo "https://DEIN-BENUTZERNAME.github.io/emilia-lernplattform/"
echo ""
echo "⚙️  GITHUB PAGES AKTIVIEREN:"
echo "=========================="
echo "1. Repository → Settings"
echo "2. Pages → Source: Deploy from a branch"
echo "3. Branch: master → Folder: /root"
echo "4. Save → 5 Minuten warten"
echo ""
echo "🎯 FERTIG! DEINE LERNPLATTFORM IST WELTWEIT ERREICHBAR! 🚀"