#!/bin/bash

echo "📅 RECHTLICHES SETUP DEUTSCHLAND - IHK Lernplattform"
echo "===================================================="
echo ""

echo "🔍 Schritt 1: Gewerbeanmeldung (Nebengewerbe)"
echo "---------------------------------------------"
echo "✅ Erforderlich für: Einkünfte aus Gewerbebetrieb"
echo "✅ Kosten: 20-60€ (je nach Gemeinde)"
echo "✅ Wo: Gewerbeamt deiner Stadt/Gemeinde"
echo "✅ Dokumente: Personalausweis, Meldebescheinigung"
echo ""
echo "📋 Formular: 'Gewerbeanmeldung' ausfüllen"
echo "🏢 Finanzamt wird automatisch informiert"
echo "📩 Steuernummer kommt per Post (2-4 Wochen)"
echo ""

echo "📝 Schritt 2: AGB (Allgemeine Geschäftsbedingungen)"
echo "-----------------------------------------------------"
echo "✅ Pflicht für Online-Verkäufe"
echo "✅ Muss enthalten: Vertragsbedingungen, Widerrufsrecht"
echo "✅ Empfehlung: Rechtsanwalt oder Vorlage von anwalt.de"
echo ""
echo "🔑 Wichtige Punkte:"
echo "- Lizenz-Bedingungen klar definieren"
echo "- Gewährleistung und Haftung"
echo "- Zahlungsbedingungen (Digistore24)"
echo "- Urheberrechte der Lerninhalte"
echo ""

echo "🛡️ Schritt 3: DSGVO (Datenschutz)"
echo "-----------------------------------"
echo "✅ Pflicht für alle Webseiten mit EU-Nutzern"
echo "✅ Benötigt: Datenschutzerklärung, Cookie-Banner"
echo "✅ Technisch: SSL-Verschlüsselung, sichere Passwörter"
echo ""
echo "📊 Erforderliche Dokumente:"
echo "- Datenschutzerklärung"
echo "- Impressum (§5 TMG)"
echo "- Cookie-Richtlinie"
echo "- Einwilligungsmanagement"
echo ""

echo "🔄 Schritt 4: Widerrufsbelehrung (14 Tage)"
echo "-------------------------------------------"
echo "✅ Gesetzlich vorgeschrieben für Online-Verkäufe"
echo "✅ Frist: 14 Tage ab Kaufdatum"
echo "✅ Form: Schriftlich oder per E-Mail"
echo ""
echo "📄 Textbaustein:"
echo "'Sie haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen.'"
echo ""

echo "💰 Schritt 5: Steuern"
echo "----------------------"
echo "✅ Einkommensteuer: Auf alle Gewinne"
echo "✅ Umsatzsteuer: 19% auf Verkäufe (bis 22.000€/Jahr optional)"
echo "✅ Gewerbesteuer: Gemeindeabhängig"
echo ""
echo "📈 Buchführungspflicht:"
echo "- Einnahmen-Überschuss-Rechnung (bis 60.000€/Jahr Umsatz)"
echo "- Doppelte Buchhaltung (darüber)"
echo "- Belege aufbewahren: 10 Jahre"
echo ""

echo "🏢 Schritt 6: Business-Konto eröffnen"
echo "--------------------------------------"
echo "✅ Pflicht: Geschäftskonto von Privatkonto trennen"
echo "✅ Empfohlen: Fintech (N26, Penta, Kontist)"
echo "✅ Kosten: 0-10€/Monat"
echo "✅ Vorteile: Buchhaltung, Steuern, Professionalität"
echo ""

echo "📱 Schritt 7: App Store Voraussetzungen"
echo "----------------------------------------"
echo "✅ Apple Developer Account: 99€/Jahr"
echo "✅ Unternehmensregistrierung (falls GmbH/UG)"
echo "✅ D-U-N-S Nummer (für Unternehmen)"
echo "✅ Steuerliche Identifikationsnummer"
echo ""

echo "🔐 Schritt 8: Rechtliche Absicherung"
echo "-------------------------------------"
echo "✅ Betriebshaftpflichtversicherung: 30-50€/Jahr"
echo "✅ Cyber-Security-Versicherung: optional"
echo "✅ Rechtschutzversicherung: optional"
echo ""

echo "📋 CHECKLISTE FÜR START:"
echo "========================"
echo "□ Gewerbe angemeldet"
echo "□ Steuernummer erhalten"
echo "□ Geschäftskonto eröffnet"
echo "□ AGB erstellt"
echo "□ Datenschutzerklärung"
echo "□ Impressum online"
echo "□ Widerrufsbelehrung"
echo "□ Apple Developer Account"
echo "□ Digistore24 Account"
echo "□ Produkte konfiguriert"
echo ""

echo "💻 NÜTZLICHE TOOLS:"
echo "==================="
echo "- anwalt.de: Rechtstexte erstellen"
echo "- clever-tanken.de: Buchhaltung"
echo "- Taxfix: Steuererklärung"
echo "- IONOS: Hosting & Impressum"
echo "- Digistore24: Verkaufsplattform"
echo ""

echo "🎯 KOSTENÜBERSICHT STARTPHASE:"
echo "=============================="
echo "Gewerbeanmeldung:      30€"
echo "Apple Developer:       99€/Jahr"
echo "Business-Konto:        0-10€/Monat"
echo "Hosting:               10€/Monat"
echo "Rechtstexte:           100-300€"
echo "Versicherung:          30€/Jahr"
echo "---------------------------"
echo "Gesamt Startkosten:    ca. 300-500€"
echo ""

echo "🚀 BIST DU BEREIT, ЗАЙЧИК? LASS UNS STARTEN!"