#!/usr/bin/env python3
"""Send a buyer-like staging/test access email via Gmail.

Requires:
  1. A real server-side access code generated by the Cloudflare Worker.
  2. Gmail send auth created with scripts/google-gmail-send.py.

The code is not logged except inside the outgoing email body.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

GMAIL_HELPER = Path(__file__).resolve().parent / "google-gmail-send.py"
CODE_RE = re.compile(r"^(IHK|PLUS)-[A-Z2-9]{4}-[A-Z2-9]{4}$")


def build_body(code: str, platform_url: str, support_email: str) -> str:
    return f"""Hallo,

vielen Dank für deinen Zugang zur Prüfungskern Lernplattform.

Dein persönlicher Zugangscode lautet:

{code}

So startest du:
1. Öffne die Lernplattform: {platform_url}
2. Klicke auf „Zugangscode eingeben“.
3. Kopiere den Code exakt aus dieser E-Mail in das Feld.
4. Danach werden die freigeschalteten Lerninhalte geladen.

Wichtig:
- Der Zugangscode ist persönlich und darf nicht weitergegeben werden.
- Bitte bewahre diese E-Mail sicher auf.
- Wenn der Code nicht funktioniert, antworte auf diese E-Mail oder schreibe an {support_email}.

Hinweis für diesen Lauf: Dies ist ein interner Testzugang zur technischen Prüfung des Kauf-/Zugangsablaufs. Es handelt sich nicht um einen echten Live-Verkauf.

Viel Erfolg beim Lernen!
Prüfungskern Team
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--code", required=True)
    parser.add_argument("--platform-url", required=True)
    parser.add_argument("--to", default="me", help="Recipient email or 'me' for connected Gmail")
    parser.add_argument("--support-email", default="support@pruefungskern.example")
    args = parser.parse_args()

    code = args.code.strip().upper()
    if not CODE_RE.fullmatch(code):
        raise SystemExit("invalid code format; expected IHK-ABCD-2345 or PLUS-ABCD-2345")

    body = build_body(code, args.platform_url.strip(), args.support_email.strip())
    cmd = [
        sys.executable,
        str(GMAIL_HELPER),
        "send",
        "--to",
        args.to,
        "--subject",
        "Dein Zugangscode zur Prüfungskern Lernplattform",
        "--body",
        body,
    ]
    subprocess.check_call(cmd)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
